REGISTER_EVENT_HANDLER = 25


POST_TO_CONSOLE = 10

PLAYER_FIND_PATH = 11
PLAYER_FOUND_PATH = 12
PLAYER_TRAVEL_PATH = 13
PLAYER_REACHED_DESTINATION = 14


GUI_TOOLTIP_POST = 20
GUI_TOOLTIP_CLEAR = 21

ITEM_INTERACT = 30

TIME_PASSED = 1000


def event_register_dict(types, handler):
    return {'event_types': types, 'handler': handler}